# Generated by Django 2.2 on 2020-02-19 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertyname",
            options={"verbose_name_plural": "property names"},
        ),
        migrations.AlterModelTable(
            name="propertyname",
            table="shop_propertyname",
        ),
    ]
