# Generated by Django 2.2 on 2020-03-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_auto_20200219_0007"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="property_name",
            field=models.ManyToManyField(blank=True, to="shop.PropertyName"),
        ),
    ]
