# Generated by Django 2.2 on 2020-05-27 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_auto_20200527_1609"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="shop.Customer"
            ),
        ),
        migrations.AlterField(
            model_name="customerorder",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="shop.Address"
            ),
        ),
        migrations.AlterField(
            model_name="customerorderitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="shop.Item"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseditem",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="shop.Customer"
            ),
        ),
    ]
