# Generated by Django 2.2 on 2020-05-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_auto_20200527_1610"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorderitem",
            name="number",
            field=models.IntegerField(default=1),
        ),
    ]
