# Generated by Django 2.2 on 2020-05-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_auto_20200528_2026"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemlog",
            old_name="type",
            new_name="log_type",
        ),
        migrations.AddField(
            model_name="customerorder",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customerorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "Order Started"),
                    ("dispatched", "Order Dispatched"),
                    ("delivered", "Order Delivered"),
                    ("cancelled", "Order Cancelled"),
                    ("returned_started", "Order Returned Started"),
                    ("returned_completed", "Order Returned"),
                    ("unknown", "Order Unknown"),
                    ("lost", "Order Lost"),
                ],
                default="started",
                max_length=20,
            ),
        ),
    ]
