# Generated by Django 2.2 on 2020-12-02 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_auto_20200610_1934"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerorder",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.Address"
            ),
        ),
        migrations.AlterField(
            model_name="customerorderitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.Item"
            ),
        ),
    ]
