# Generated by Django 2.2 on 2020-06-27 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "carousel_image_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=False)),
                ("image", models.ImageField(upload_to="carousel/")),
            ],
            options={
                "verbose_name_plural": "carousel image",
                "db_table": "carousel_image",
            },
        ),
        migrations.CreateModel(
            name="ContentText",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "alias",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("content", models.TextField()),
                ("active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "footer_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "alias",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                ("heading", models.TextField()),
                ("content", models.TextField()),
            ],
            options={
                "verbose_name_plural": "footer content",
                "db_table": "footer_content",
            },
        ),
        migrations.CreateModel(
            name="Navigation",
            fields=[
                (
                    "navigation_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "alias",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "navigation_type",
                    models.CharField(
                        choices=[
                            ("tp", "Top Navigation"),
                            ("si", "Side Navigation"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "navigation",
                "db_table": "navigation",
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "page_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "alias",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "social_media_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("display_text", models.TextField(default="")),
                ("link", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=False)),
                ("display_in_footer", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "social media",
                "db_table": "social_media",
            },
        ),
        migrations.CreateModel(
            name="NavigationLink",
            fields=[
                (
                    "navigation_link_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "alias",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("url", models.CharField(max_length=255)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms.Page",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "navigation link",
                "db_table": "navigation_link",
            },
        ),
        migrations.CreateModel(
            name="ContentManagement",
            fields=[
                (
                    "content_management_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "footer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cms.Footer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "content management",
                "db_table": "content_management",
            },
        ),
    ]
