# Generated by Django 2.2 on 2020-06-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselimage",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
