# Generated by Django 2.2 on 2020-05-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
