# Generated by Django 2.2 on 2020-05-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_delete_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseditem",
            name="item",
        ),
        migrations.RemoveField(
            model_name="purchaseditem",
            name="user",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="item",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="user",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
        migrations.DeleteModel(
            name="PurchasedItem",
        ),
        migrations.DeleteModel(
            name="WishList",
        ),
    ]
